on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: >-
        a
        b
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ github.event.deployment.environment }}"