on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: ${{ steps.set_env.outputs.A }}
    steps:

      - id: set_env
        run: echo A=$'A\n' | tee $GITHUB_ENV

      - name: Deploy
        run: echo "Deploying to ${{ github.event.deployment.environment }}"