on:
  push:

jobs:

  prepareEnv:
    runs-on: ubuntu-22.04
    outputs:
      A: ${{ steps.set_env.outputs.A }}
    steps:
      - id: set_env
        run: echo A=$'A\n' | tee $GITHUB_ENV

  deploy:
    runs-on: ubuntu-22.04
    needs: [prepareEnv]
    environment:
      name: ${{ needs.prepareEnv.outputs.A }}
    steps:

      - name: Deploy
        run: echo "Deploying to ${{ github.event.deployment.environment }}"